name: Teleporters
version: '1.1-SNAPSHOT'
main: org.leminegaming.teleporters.Teleporters
api-version: '1.21'
authors: [ leMineGaming ]
description: Minecraft Plugin that creates teleporters to other positions.
website: http://teleporters.leminegaming.software
